version: 2
jobs:
  build:
    docker:
      - image: oliverlundquist/php7:latest
        environment:
          APP_URL: http://localhost
          APP_ENV: testing
          APP_DEBUG: true
          APP_KEY: base64:/WoPNs10wRuzDcu1G+t5b0uzMmCWvygWcP80vJTyX28=
          DB_CONNECTION: mysql
          DB_HOST: 0.0.0.0
          DB_PORT: 3306
          DB_DATABASE: circleci
          DB_USERNAME: root
          DB_PASSWORD: root
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: circleci
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run: apt-get install -y zlib1g-dev libzip-dev
      - run: docker-php-ext-install zip
      - run: curl -sS https://getcomposer.org/installer | php
      - run: mv composer.phar /usr/local/bin/composer
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - run: php artisan dusk
      - deploy:
          name: "Deploy to Production"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # deploying logic here
              echo "deploying"
            else
              echo "not deploying"
            fi
