defaults: &defaults
  docker:
    - image: oliverlundquist/php7:latest
      environment:
        APP_URL: http://0.0.0.0:9000
        APP_ENV: testing
        APP_DEBUG: true
        APP_KEY: base64:/WoPNs10wRuzDcu1G+t5b0uzMmCWvygWcP80vJTyX28=
        DB_CONNECTION: mysql
        DB_HOST: 0.0.0.0
        DB_PORT: 3306
        DB_DATABASE: circleci
        DB_USERNAME: root
        DB_PASSWORD: root
    - image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: circleci
    - image: selenium/standalone-chrome:latest

version: 2
jobs:
  setup:
    <<: *defaults
    steps:
      - run: apt-get install -y git
      - checkout
      - run: curl -sS https://getcomposer.org/installer | php
      - run: mv composer.phar /usr/local/bin/composer
      - run: composer self-update
      - run: composer install -n --prefer-dist

  chrome:
    <<: *defaults
    steps:
      - run:
          command: php artisan serve --host=0.0.0.0 --port=9000
          background: true
      - run: php artisan dusk

  firefox:
    <<: *defaults
    steps:
      - run:
          command: php artisan serve --host=0.0.0.0 --port=9000
          background: true
      - run: php artisan dusk

  teardown:
    <<: *defaults
    steps:
      - store_artifacts:
          path: tests/Browser/screenshots
      - store_artifacts:
          path: storage/logs

  deploy:
    <<: *defaults
    steps:
      - deploy:
          name: "Deploy to Production"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # deploying logic here
              echo "deploying"
            else
              echo "not deploying"
            fi

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - setup
      - chrome:
          requires:
            - setup
      - firefox:
          requires:
            - setup
      - teardown:
          requires:
            - chrome
            - firefox
      - deploy:
          requires:
            - chrome
            - firefox
