docker: &docker
  docker:
    - image: oliverlundquist/php7:latest
      environment:
        APP_URL: http://0.0.0.0:9000
        APP_ENV: testing
        APP_DEBUG: true
        APP_KEY: base64:/WoPNs10wRuzDcu1G+t5b0uzMmCWvygWcP80vJTyX28=
        DB_CONNECTION: mysql
        DB_HOST: 0.0.0.0
        DB_PORT: 3306
        DB_DATABASE: circleci
        DB_USERNAME: root
        DB_PASSWORD: root
    - image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: circleci
    - image: selenium/standalone-chrome:latest

version: 2
jobs:
  build:
    <<: *docker
    steps:
      - checkout
      - run: curl -sS https://getcomposer.org/installer | php
      - run: mv composer.phar /usr/local/bin/composer
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
      - run: composer install -o -n --prefer-dist
      # - run:
      #     command: |
      #       if [ ! -d vendorz ]; then
      #         composer install -o -n --prefer-dist
      #       fi
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: /usr/local/bin
          paths:
            - composer

  chrome:
    <<: *docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
      - attach_workspace:
          at: /usr/local/bin
      - run:
          command: php artisan serve --host=0.0.0.0 --port=9000
          background: true
      - run: php artisan dusk
      - store_artifacts:
          path: tests/Browser/screenshots
      - store_artifacts:
          path: storage/logs

  firefox:
    <<: *docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
      - attach_workspace:
          at: /usr/local/bin
      - run:
          command: php artisan serve --host=0.0.0.0 --port=9000
          background: true
      - run: php artisan dusk
      - store_artifacts:
          path: tests/Browser/screenshots
      - store_artifacts:
          path: storage/logs

  deploy:
    <<: *docker
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
      - deploy:
          name: "Deploy to Production"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # deploying logic here
              echo "deploying"
            else
              echo "not deploying"
            fi

workflows:
  version: 2
  test_teardown_deploy:
    jobs:
      - build
      - chrome:
          requires:
            - build
      - firefox:
          requires:
            - build
      - deploy:
          requires:
            - chrome
            - firefox
