php_environment: &php_environment
  environment:
    APP_URL: http://0.0.0.0:9000
    APP_ENV: testing
    APP_DEBUG: true
    APP_KEY: base64:/WoPNs10wRuzDcu1G+t5b0uzMmCWvygWcP80vJTyX28=
    DB_CONNECTION: mysql
    DB_HOST: 0.0.0.0
    DB_PORT: 3306
    DB_DATABASE: circleci
    DB_USERNAME: root
    DB_PASSWORD: root

mysql_environment: &mysql_environment
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: circleci

version: 2
jobs:
  build:
    docker:
      - image: oliverlundquist/php7:latest
        <<: *php_environment
    steps:
      - checkout
      - run: curl -sS https://getcomposer.org/installer | php
      - run: mv composer.phar /usr/local/bin/composer
      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
      - run: composer install -o -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor
      - persist_to_workspace:
          root: /usr/local/bin
          paths:
            - composer

  chrome:
    docker:
      - image: oliverlundquist/php7:latest
        <<: *php_environment
      - image: mysql:5.7
        <<: *mysql_environment
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
      - attach_workspace:
          at: /usr/local/bin
      - run:
          command: php artisan serve --host=0.0.0.0 --port=9000
          background: true
      - run: TEST_BROWSER=chrome php artisan dusk
      - store_artifacts:
          path: tests/Browser/screenshots
      - store_artifacts:
          path: storage/logs

  firefox:
    docker:
      - image: oliverlundquist/php7:latest
        <<: *php_environment
      - image: mysql:5.7
        <<: *mysql_environment
      - image: selenium/standalone-firefox:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
      - attach_workspace:
          at: /usr/local/bin
      - run:
          command: php artisan serve --host=0.0.0.0 --port=9000
          background: true
      - run: TEST_BROWSER=firefox php artisan dusk
      - store_artifacts:
          path: tests/Browser/screenshots
      - store_artifacts:
          path: storage/logs

  ie:
    docker:
      - image: oliverlundquist/php7:latest
        <<: *php_environment
      - image: mysql:5.7
        <<: *mysql_environment
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
      - attach_workspace:
          at: /usr/local/bin
      - run:
          command: php artisan serve --host=0.0.0.0 --port=9000
          background: true
      - run: TEST_BROWSER=IE php artisan dusk
      - store_artifacts:
          path: tests/Browser/screenshots
      - store_artifacts:
          path: storage/logs

  deploy:
    docker:
      - image: oliverlundquist/php7:latest
        <<: *php_environment
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
      - deploy:
          name: "Deploy to Production"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # deploying logic here
              echo "deploying"
            else
              echo "not deploying"
            fi

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - chrome:
          requires:
            - build
      - firefox:
          requires:
            - build
      - ie:
          requires:
            - build
      - deploy:
          requires:
            - chrome
            - firefox
            - ie
