version: 2
jobs:
  build:
    docker:
      #- image: circleci/php:7.1.8-browsers
      - image: oliverlundquist/php7:latest
      - image: oliverlundquist/nginx:latest
      - image: mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: circleci
      - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      - run: pwd
      - run: which php
      - run: php -v
      # - run: curl nginx
      # - run: wget --retry-connrefused --waitretry=5 -t 10 nginx
      # - run: wget --retry-connrefused --waitretry=5 -t 10 mysql
      # - run: wget --retry-connrefused --waitretry=5 -t 10 selenium
      # - run: cat /etc/hosts
      - deploy:
          name: "Deploy to Production"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # deploying logic here
              echo "deploying"
            else
              echo "not deploying"
            fi
