docker: &docker
  docker:
    - image: oliverlundquist/php7:latest
      environment:
        APP_URL: http://0.0.0.0:9000
        APP_ENV: testing
        APP_DEBUG: true
        APP_KEY: base64:/WoPNs10wRuzDcu1G+t5b0uzMmCWvygWcP80vJTyX28=
        DB_CONNECTION: mysql
        DB_HOST: 0.0.0.0
        DB_PORT: 3306
        DB_DATABASE: circleci
        DB_USERNAME: root
        DB_PASSWORD: root
    - image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: circleci
    - image: selenium/standalone-chrome:latest

composer: &composer
    steps:
      - run: apt-get install -y git
      - checkout
      - run: curl -sS https://getcomposer.org/installer | php
      - run: mv composer.phar /usr/local/bin/composer
      - run: composer self-update
      - run: composer install -n --prefer-dist

      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory
          root: workspace
          # Must be relative path from root
          paths:
            - echo-output

version: 2
jobs:
  composer:
    <<: *docker
    steps:
      - run: curl -sS https://getcomposer.org/installer | php
      - run: mv composer.phar /usr/local/bin/composer
      - run: composer self-update
      - persist_to_workspace:
          root: /usr/local/bin
          paths:
            - composer

  chrome:
    <<: *docker
    steps:
      - attach_workspace:
          at: /usr/local/bin
      - run: apt-get install -y git
      - checkout
      - run: composer install -n --prefer-dist
      - run:
          command: php artisan serve --host=0.0.0.0 --port=9000
          background: true
      - run: php artisan dusk
      - store_artifacts:
          path: tests/Browser/screenshots
      - store_artifacts:
          path: storage/logs

  firefox:
    <<: *docker
    steps:
      - attach_workspace:
          at: /usr/local/bin
      - run: apt-get install -y git
      - checkout
      - run: composer install -n --prefer-dist
      - run:
          command: php artisan serve --host=0.0.0.0 --port=9000
          background: true
      - run: php artisan dusk
      - store_artifacts:
          path: tests/Browser/screenshots
      - store_artifacts:
          path: storage/logs

  deploy:
    <<: *docker
    steps:
      - deploy:
          name: "Deploy to Production"
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # deploying logic here
              echo "deploying"
            else
              echo "not deploying"
            fi

workflows:
  version: 2
  test_teardown_deploy:
    jobs:
      - composer
      - chrome:
          requires:
            - composer
      - firefox:
          requires:
            - composer
      - deploy:
          requires:
            - chrome
            - firefox
